version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oxyno-zeta/prometheus-cachethq
    steps:
      - checkout
      - run: make lint
      - save_cache:
          key: go-mod-{{ checksum "go.mod"  }}
          paths:
            - "/go/pkg/"
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oxyno-zeta/prometheus-cachethq
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make build
  build-cross:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oxyno-zeta/prometheus-cachethq
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make build-cross
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oxyno-zeta/prometheus-cachethq
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.mod"  }}
      - run: make test
workflows:
  version: 2
  project:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - build-cross:
          requires:
            - lint
      - test:
          requires:
            - lint
